// Standard Atomic Weights — IUPAC 2021
// Source: Commission on Isotopic Abundances and Atomic Weights (CIAAW)
//         https://ciaaw.org/atomic-weights.htm (2021 table)
//
// Conventions used:
//   • For elements with isotopically variable compositions (H, Li, B, C, N, O, Mg,
//     Si, S, Cl, Tl), IUPAC publishes an interval [a, b]. We use the conventional
//     representative value published by IUPAC.
//   • For elements with no stable isotopes (Tc, Pm, Po, At, Rn, Fr, Ra, Ac, and
//     transuranic elements), we use the atomic mass of the most stable / most
//     commonly referenced isotope, indicated by the 'radioactive: true' flag.
//     These values are approximate and suitable for laboratory MW calculations.
//     Reference: IUPAC recommendations and NUBASE2020 evaluation.

export interface ElementData {
  name: string
  mass: number        // g/mol, IUPAC 2021 (or conventional mass for radioactive)
  radioactive?: true  // set when no stable isotope exists
}

export const ELEMENTS: Record<string, ElementData> = {
  H:  { name: 'Hydrogen',      mass: 1.008    },
  He: { name: 'Helium',        mass: 4.0026   },
  Li: { name: 'Lithium',       mass: 6.94     },
  Be: { name: 'Beryllium',     mass: 9.0122   },
  B:  { name: 'Boron',         mass: 10.81    },
  C:  { name: 'Carbon',        mass: 12.011   },
  N:  { name: 'Nitrogen',      mass: 14.007   },
  O:  { name: 'Oxygen',        mass: 15.999   },
  F:  { name: 'Fluorine',      mass: 18.998   },
  Ne: { name: 'Neon',          mass: 20.180   },
  Na: { name: 'Sodium',        mass: 22.990   },
  Mg: { name: 'Magnesium',     mass: 24.305   },
  Al: { name: 'Aluminium',     mass: 26.982   },
  Si: { name: 'Silicon',       mass: 28.085   },
  P:  { name: 'Phosphorus',    mass: 30.974   },
  S:  { name: 'Sulfur',        mass: 32.06    },
  Cl: { name: 'Chlorine',      mass: 35.45    },
  Ar: { name: 'Argon',         mass: 39.948   },
  K:  { name: 'Potassium',     mass: 39.098   },
  Ca: { name: 'Calcium',       mass: 40.078   },
  Sc: { name: 'Scandium',      mass: 44.956   },
  Ti: { name: 'Titanium',      mass: 47.867   },
  V:  { name: 'Vanadium',      mass: 50.942   },
  Cr: { name: 'Chromium',      mass: 51.996   },
  Mn: { name: 'Manganese',     mass: 54.938   },
  Fe: { name: 'Iron',          mass: 55.845   },
  Co: { name: 'Cobalt',        mass: 58.933   },
  Ni: { name: 'Nickel',        mass: 58.693   },
  Cu: { name: 'Copper',        mass: 63.546   },
  Zn: { name: 'Zinc',          mass: 65.38    },
  Ga: { name: 'Gallium',       mass: 69.723   },
  Ge: { name: 'Germanium',     mass: 72.630   },
  As: { name: 'Arsenic',       mass: 74.922   },
  Se: { name: 'Selenium',      mass: 78.971   },
  Br: { name: 'Bromine',       mass: 79.904   },
  Kr: { name: 'Krypton',       mass: 83.798   },
  Rb: { name: 'Rubidium',      mass: 85.468   },
  Sr: { name: 'Strontium',     mass: 87.62    },
  Y:  { name: 'Yttrium',       mass: 88.906   },
  Zr: { name: 'Zirconium',     mass: 91.224   },
  Nb: { name: 'Niobium',       mass: 92.906   },
  Mo: { name: 'Molybdenum',    mass: 95.95    },
  Tc: { name: 'Technetium',    mass: 97,       radioactive: true },
  Ru: { name: 'Ruthenium',     mass: 101.07   },
  Rh: { name: 'Rhodium',       mass: 102.91   },
  Pd: { name: 'Palladium',     mass: 106.42   },
  Ag: { name: 'Silver',        mass: 107.87   },
  Cd: { name: 'Cadmium',       mass: 112.41   },
  In: { name: 'Indium',        mass: 114.82   },
  Sn: { name: 'Tin',           mass: 118.71   },
  Sb: { name: 'Antimony',      mass: 121.76   },
  Te: { name: 'Tellurium',     mass: 127.60   },
  I:  { name: 'Iodine',        mass: 126.90   },
  Xe: { name: 'Xenon',         mass: 131.29   },
  Cs: { name: 'Caesium',       mass: 132.91   },
  Ba: { name: 'Barium',        mass: 137.33   },
  La: { name: 'Lanthanum',     mass: 138.91   },
  Ce: { name: 'Cerium',        mass: 140.12   },
  Pr: { name: 'Praseodymium',  mass: 140.91   },
  Nd: { name: 'Neodymium',     mass: 144.24   },
  Pm: { name: 'Promethium',    mass: 145,      radioactive: true },
  Sm: { name: 'Samarium',      mass: 150.36   },
  Eu: { name: 'Europium',      mass: 151.96   },
  Gd: { name: 'Gadolinium',    mass: 157.25   },
  Tb: { name: 'Terbium',       mass: 158.93   },
  Dy: { name: 'Dysprosium',    mass: 162.50   },
  Ho: { name: 'Holmium',       mass: 164.93   },
  Er: { name: 'Erbium',        mass: 167.26   },
  Tm: { name: 'Thulium',       mass: 168.93   },
  Yb: { name: 'Ytterbium',     mass: 173.05   },
  Lu: { name: 'Lutetium',      mass: 174.97   },
  Hf: { name: 'Hafnium',       mass: 178.49   },
  Ta: { name: 'Tantalum',      mass: 180.95   },
  W:  { name: 'Tungsten',      mass: 183.84   },
  Re: { name: 'Rhenium',       mass: 186.21   },
  Os: { name: 'Osmium',        mass: 190.23   },
  Ir: { name: 'Iridium',       mass: 192.22   },
  Pt: { name: 'Platinum',      mass: 195.08   },
  Au: { name: 'Gold',          mass: 196.97   },
  Hg: { name: 'Mercury',       mass: 200.59   },
  Tl: { name: 'Thallium',      mass: 204.38   },
  Pb: { name: 'Lead',          mass: 207.2    },
  Bi: { name: 'Bismuth',       mass: 208.98   },
  Po: { name: 'Polonium',      mass: 209,      radioactive: true },
  At: { name: 'Astatine',      mass: 210,      radioactive: true },
  Rn: { name: 'Radon',         mass: 222,      radioactive: true },
  Fr: { name: 'Francium',      mass: 223,      radioactive: true },
  Ra: { name: 'Radium',        mass: 226,      radioactive: true },
  Ac: { name: 'Actinium',      mass: 227,      radioactive: true },
  Th: { name: 'Thorium',       mass: 232.04   },
  Pa: { name: 'Protactinium',  mass: 231.04   },
  U:  { name: 'Uranium',       mass: 238.03   },
  Np: { name: 'Neptunium',     mass: 237,      radioactive: true },
  Pu: { name: 'Plutonium',     mass: 244,      radioactive: true },
  Am: { name: 'Americium',     mass: 243,      radioactive: true },
  Cm: { name: 'Curium',        mass: 247,      radioactive: true },
  Bk: { name: 'Berkelium',     mass: 247,      radioactive: true },
  Cf: { name: 'Californium',   mass: 251,      radioactive: true },
  Es: { name: 'Einsteinium',   mass: 252,      radioactive: true },
  Fm: { name: 'Fermium',       mass: 257,      radioactive: true },
  Md: { name: 'Mendelevium',   mass: 258,      radioactive: true },
  No: { name: 'Nobelium',      mass: 259,      radioactive: true },
  Lr: { name: 'Lawrencium',    mass: 262,      radioactive: true },
  Rf: { name: 'Rutherfordium', mass: 267,      radioactive: true },
  Db: { name: 'Dubnium',       mass: 268,      radioactive: true },
  Sg: { name: 'Seaborgium',    mass: 271,      radioactive: true },
  Bh: { name: 'Bohrium',       mass: 270,      radioactive: true },
  Hs: { name: 'Hassium',       mass: 277,      radioactive: true },
  Mt: { name: 'Meitnerium',    mass: 278,      radioactive: true },
  Ds: { name: 'Darmstadtium',  mass: 281,      radioactive: true },
  Rg: { name: 'Roentgenium',   mass: 282,      radioactive: true },
  Cn: { name: 'Copernicium',   mass: 285,      radioactive: true },
  Nh: { name: 'Nihonium',      mass: 286,      radioactive: true },
  Fl: { name: 'Flerovium',     mass: 289,      radioactive: true },
  Mc: { name: 'Moscovium',     mass: 290,      radioactive: true },
  Lv: { name: 'Livermorium',   mass: 293,      radioactive: true },
  Ts: { name: 'Tennessine',    mass: 294,      radioactive: true },
  Og: { name: 'Oganesson',     mass: 294,      radioactive: true },
}
