import type { FigureTemplate } from './types'

export const FIGURE_TEMPLATES: FigureTemplate[] = [
  {
    id: 'builtin-scatter-publication',
    name: 'Publication Scatter',
    builtIn: true,
    description: 'Individual data points with clean ACS-style axes. No grid, no clutter — just your data.',
    category: 'scientific',
    chartType: 'scatter',
    previewImage: '/templates/scatter-publication.svg',
    requiredDataRoles: { x: true, y: true, error: false },
    defaultAxisLabels: { x: 'X', y: 'Y' },
    overrides: {
      fontFamily: 'Arial, Helvetica, sans-serif',
      xTitleSize: 18,
      yTitleSize: 18,
      xTickSize: 16,
      yTickSize: 16,
      axisWidth: 1.5,
      axisColor: '#000000',
      showGrid: false,
      boldLabels: false,
      showLegend: false,
      figureWidth: 700,
      figureHeight: 440,
    },
    seriesColorsList: ['#000000'],
    seriesMarkerSizesList: [5],
    seriesMarkerShapesList: ['circle'],
  },
  {
    id: 'builtin-timecourse-line',
    name: 'Time-course Line',
    builtIn: true,
    description: 'Multi-series line plot with distinct markers. Ideal for kinetics and time-series experiments.',
    category: 'time-series',
    chartType: 'line',
    previewImage: '/templates/timecourse-line.svg',
    requiredDataRoles: { x: true, y: true, group: true, error: false },
    defaultAxisLabels: { x: 'Time (s)', y: 'Signal (a.u.)' },
    overrides: {
      fontFamily: 'Arial, Helvetica, sans-serif',
      xTitleSize: 18,
      yTitleSize: 18,
      xTickSize: 16,
      yTickSize: 16,
      axisWidth: 1.5,
      axisColor: '#000000',
      showGrid: true,
      boldLabels: false,
      showLegend: true,
      legendPosition: 'top',
      legendFontSize: 14,
      legendOrientation: 'h',
      legendBg: false,
      figureWidth: 700,
      figureHeight: 440,
    },
    seriesColorsList: ['#1F4FA8', '#E2211C', '#1B9E4B'],
    seriesStrokeWidthsList: [2, 2, 2],
    seriesMarkerSizesList: [4, 4, 4],
    seriesMarkerShapesList: ['circle', 'square', 'triangle'],
  },
  {
    id: 'builtin-bar-sem',
    name: 'Bar + SEM',
    builtIn: true,
    description: 'Bar chart with standard error bars. Clean axes, no grid — standard for group comparisons.',
    category: 'comparison',
    chartType: 'bar',
    previewImage: '/templates/bar-sem.svg',
    requiredDataRoles: { x: true, y: true, error: true },
    defaultAxisLabels: { x: 'Group', y: 'Mean ± SEM' },
    overrides: {
      fontFamily: 'Arial, Helvetica, sans-serif',
      xTitleSize: 18,
      yTitleSize: 18,
      xTickSize: 16,
      yTickSize: 16,
      axisWidth: 1.5,
      axisColor: '#000000',
      showGrid: false,
      boldLabels: false,
      showLegend: false,
      figureWidth: 700,
      figureHeight: 440,
    },
    seriesColorsList: ['#6b7280'],
    seriesStrokeWidthsList: [1.5],
  },
]
