import type { FigureTemplate } from './types'

export const FIGURE_TEMPLATES: FigureTemplate[] = [
  {
    id: 'builtin-dose-response',
    name: 'Dose-Response (IC₅₀)',
    builtIn: true,
    description: 'Sigmoidal inhibition curve on a log-concentration axis. Standard for IC₅₀ and EC₅₀ determination in pharmacology and oncology.',
    category: 'dose-response',
    chartType: 'scatter',
    previewImage: '/templates/dose-response.svg',
    requiredDataRoles: { x: true, y: true, error: true },
    defaultAxisLabels: { x: 'Compound A (µM)', y: 'Cell viability (%)' },
    overrides: {
      fontFamily: 'Arial, Helvetica, sans-serif',
      xTitleSize: 18,
      yTitleSize: 18,
      xTickSize: 16,
      yTickSize: 16,
      axisWidth: 1.5,
      axisColor: '#000000',
      showGrid: false,
      boldLabels: false,
      showLegend: false,
      xScale: 'log',
      yScale: 'linear',
      figureWidth: 700,
      figureHeight: 440,
    },
    seriesColorsList: ['#111827'],
    seriesMarkerShapesList: ['circle'],
    seriesMarkerSizesList: [5],
    seriesStrokeWidthsList: [1.5],
  },
  {
    id: 'builtin-growth-kinetics',
    name: 'Bacterial Growth Kinetics',
    builtIn: true,
    description: 'Multi-strain growth curves with SEM error bars. Ideal for comparing WT vs knockouts in OD₆₀₀ or CFU time-course experiments.',
    category: 'time-course',
    chartType: 'line',
    previewImage: '/templates/growth-kinetics.svg',
    requiredDataRoles: { x: true, y: true, error: true },
    defaultAxisLabels: { x: 'Time (h)', y: 'OD₆₀₀' },
    overrides: {
      fontFamily: 'Arial, Helvetica, sans-serif',
      xTitleSize: 18,
      yTitleSize: 18,
      xTickSize: 16,
      yTickSize: 16,
      axisWidth: 1.5,
      axisColor: '#000000',
      showGrid: false,
      boldLabels: false,
      showLegend: true,
      legendPosition: 'right',
      legendFontSize: 13,
      legendOrientation: 'v',
      legendBg: false,
      figureWidth: 700,
      figureHeight: 440,
    },
    seriesColorsList: ['#1a1a1a', '#2563EB', '#DC2626'],
    seriesStrokeWidthsList: [1.5, 1.5, 1.5],
    seriesMarkerSizesList: [4, 4, 4],
    seriesMarkerShapesList: ['circle', 'square', 'triangle'],
  },
  {
    id: 'builtin-qpcr-expression',
    name: 'qPCR Gene Expression',
    builtIn: true,
    description: 'Normalized mRNA fold change across treatment conditions. Bar chart with SEM — the standard format for qRT-PCR and Western blot quantification.',
    category: 'comparison',
    chartType: 'bar',
    previewImage: '/templates/qpcr-expression.svg',
    requiredDataRoles: { x: true, y: true, error: true },
    defaultAxisLabels: { x: 'Treatment', y: 'Relative mRNA (fold change)' },
    overrides: {
      fontFamily: 'Arial, Helvetica, sans-serif',
      xTitleSize: 18,
      yTitleSize: 18,
      xTickSize: 16,
      yTickSize: 16,
      axisWidth: 1.5,
      axisColor: '#000000',
      showGrid: false,
      boldLabels: false,
      showLegend: false,
      figureWidth: 700,
      figureHeight: 440,
    },
    seriesColorsList: ['#9CA3AF'],
    seriesStrokeWidthsList: [1.5],
  },
  {
    id: 'builtin-biomarker-correlation',
    name: 'Biomarker Correlation',
    builtIn: true,
    description: 'Two-group scatter plot correlating clinical biomarkers. Healthy vs disease populations — for immunology, clinical research, and proteomics.',
    category: 'correlation',
    chartType: 'scatter',
    previewImage: '/templates/biomarker-correlation.svg',
    requiredDataRoles: { x: true, y: true, group: true },
    defaultAxisLabels: { x: 'CRP (mg/L)', y: 'IL-6 (pg/mL)' },
    overrides: {
      fontFamily: 'Arial, Helvetica, sans-serif',
      xTitleSize: 18,
      yTitleSize: 18,
      xTickSize: 16,
      yTickSize: 16,
      axisWidth: 1.5,
      axisColor: '#000000',
      showGrid: false,
      boldLabels: false,
      showLegend: true,
      legendPosition: 'right',
      legendFontSize: 13,
      legendOrientation: 'v',
      legendBg: false,
      figureWidth: 700,
      figureHeight: 440,
    },
    seriesColorsList: ['#2563EB', '#DC2626'],
    seriesMarkerShapesList: ['circle', 'square'],
    seriesMarkerSizesList: [5, 5],
    seriesStrokeWidthsList: [0, 0],
  },
  {
    id: 'builtin-tumor-volume',
    name: 'Tumor Volume — In Vivo',
    builtIn: true,
    description: 'Longitudinal tumor growth under four treatment arms. The standard figure for in vivo efficacy studies in oncology and pharmacology.',
    category: 'time-course',
    chartType: 'line',
    previewImage: '/templates/tumor-volume.svg',
    requiredDataRoles: { x: true, y: true, error: true },
    defaultAxisLabels: { x: 'Days post-inoculation', y: 'Tumor volume (mm³)' },
    overrides: {
      fontFamily: 'Arial, Helvetica, sans-serif',
      xTitleSize: 18,
      yTitleSize: 18,
      xTickSize: 16,
      yTickSize: 16,
      axisWidth: 1.5,
      axisColor: '#000000',
      showGrid: false,
      boldLabels: false,
      showLegend: true,
      legendPosition: 'right',
      legendFontSize: 13,
      legendOrientation: 'v',
      legendBg: false,
      figureWidth: 700,
      figureHeight: 440,
    },
    seriesColorsList: ['#111827', '#2563EB', '#DC2626', '#16A34A'],
    seriesMarkerShapesList: ['circle', 'square', 'diamond', 'triangle'],
    seriesMarkerSizesList: [4, 4, 4, 4],
    seriesStrokeWidthsList: [1.5, 1.5, 1.5, 1.5],
  },
  {
    id: 'builtin-uv-vis-absorption',
    name: 'UV–Vis Absorption Spectra',
    builtIn: true,
    description: 'Absorbance spectra versus wavelength. Overlay by default for quantitative comparison — stacking available for multi-sample presentation.',
    category: 'spectra',
    chartType: 'lineOnly',
    previewImage: '/templates/uv-vis-absorption.svg',
    requiredDataRoles: { x: true, y: true },
    defaultAxisLabels: { x: 'Wavelength (nm)', y: 'Absorbance (a.u.)' },
    overrides: {
      fontFamily: 'Arial, Helvetica, sans-serif',
      xTitleSize: 18,
      yTitleSize: 18,
      xTickSize: 16,
      yTickSize: 16,
      axisWidth: 1.5,
      axisColor: '#000000',
      showGrid: false,
      boldLabels: false,
      showLegend: true,
      legendPosition: 'right',
      legendFontSize: 13,
      legendOrientation: 'v',
      legendBg: false,
      figureWidth: 700,
      figureHeight: 440,
      yMin: 0,
    },
    seriesColorsList: ['#2166ac', '#ca0020', '#1a9850', '#7b2d8b'],
    seriesStrokeWidthsList: [1.5, 1.5, 1.5, 1.5],
    seriesMarkerSizesList: [0, 0, 0, 0],
  },
  {
    id: 'builtin-fluorescence-spectra',
    name: 'Fluorescence Emission Spectra',
    builtIn: true,
    description: 'Normalized emission profiles of three fluorophores over wavelength. Standard for spectroscopy, FRET assays, and fluorescence microscopy characterization.',
    category: 'spectra',
    chartType: 'lineOnly',
    previewImage: '/templates/fluorescence-spectra.svg',
    requiredDataRoles: { x: true, y: true },
    defaultAxisLabels: { x: 'Wavelength (nm)', y: 'Intensity (a.u.)' },
    overrides: {
      fontFamily: 'Arial, Helvetica, sans-serif',
      xTitleSize: 18,
      yTitleSize: 18,
      xTickSize: 16,
      yTickSize: 16,
      axisWidth: 1.5,
      axisColor: '#000000',
      showGrid: false,
      boldLabels: false,
      showLegend: true,
      legendPosition: 'right',
      legendFontSize: 13,
      legendOrientation: 'v',
      legendBg: false,
      figureWidth: 700,
      figureHeight: 440,
    },
    seriesColorsList: ['#0891B2', '#16A34A', '#DC2626'],
    seriesStrokeWidthsList: [2, 2, 2],
    seriesMarkerSizesList: [0, 0, 0],
  },
]
